# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sc_gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype', models.CharField(max_length=12)),
                ('dname', models.CharField(default='\u73af\u6cf0\u8bbe\u5907', max_length=16)),
                ('dmac', models.CharField(max_length=40)),
                ('dbrand', models.CharField(default='', max_length=20)),
                ('gcontrolcode', models.CharField(default='', max_length=10)),
                ('ggateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc_gateway.GatewayInfo')),
            ],
        ),
    ]
