# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uname',
            field=models.CharField(default='\u73af\u6cf0', max_length=20),
        ),
    ]
