# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sc_user', '0002_auto_20170826_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(default='\u73af\u6cf0\u7f51\u5173', max_length=16)),
                ('gmac', models.CharField(max_length=40)),
                ('gpasscode', models.CharField(default='', max_length=24)),
                ('gdid', models.CharField(default='', max_length=16)),
                ('guser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc_user.UserInfo')),
            ],
        ),
    ]
